CREATE TABLE nhl (team TEXT PRIMARY KEY,short TEXT,full TEXT,conf TEXT,div TEXT);
INSERT INTO nhl (team,short,full,conf,div) values ('ANA','Ducks','Anaheim Ducks','Western','Pacific');
INSERT INTO nhl (team,short,full,conf,div) values ('BOS','Bruins','Boston Bruins','Eastern','Northeast');
INSERT INTO nhl (team,short,full,conf,div) values ('BUF','Sabres','Buffalo Sabres','Eastern','Northeast');
INSERT INTO nhl (team,short,full,conf,div) values ('CGY','Flames','Calgary Flames','Western','Northwest');
INSERT INTO nhl (team,short,full,conf,div) values ('CAR','Hurricanes','Carolina Hurricanes','Eastern','Southeast');
INSERT INTO nhl (team,short,full,conf,div) values ('CHI','Blackhawks','Chicago Blackhawks','Western','Central');
INSERT INTO nhl (team,short,full,conf,div) values ('COL','Avalanche','Colorado Avalanche','Western','Northwest');
INSERT INTO nhl (team,short,full,conf,div) values ('CBJ','BlueJackets','Columbus Bluejackets','Western','Central');
INSERT INTO nhl (team,short,full,conf,div) values ('DAL','Stars','Dallas Stars','Western','Pacific');
INSERT INTO nhl (team,short,full,conf,div) values ('DET','RedWings','Detroit Red Wings','Western','Central');
INSERT INTO nhl (team,short,full,conf,div) values ('EDM','Oilers','Edmonton Oilers','Western','Northwest');
INSERT INTO nhl (team,short,full,conf,div) values ('FLA','Panthers','Florida Panthers','Eastern','Florida');
INSERT INTO nhl (team,short,full,conf,div) values ('LAK','Kings','Los Angeles Kings','Western','Pacific');
INSERT INTO nhl (team,short,full,conf,div) values ('MIN','Wild','Minnesota Wild','Western','Northwest');
INSERT INTO nhl (team,short,full,conf,div) values ('MTL','Canadiens','Montreal Canadiens','Eastern','Northeast');
INSERT INTO nhl (team,short,full,conf,div) values ('NSH','Predators','Nashville Predators','Western','Central');
INSERT INTO nhl (team,short,full,conf,div) values ('NJD','Devils','New Jersey Devils','Eastern','Atlantic');
INSERT INTO nhl (team,short,full,conf,div) values ('NYI','Islanders','New York Islanders','Eastern','Atlantic');
INSERT INTO nhl (team,short,full,conf,div) values ('NYR','Rangers','New York Rangers','Eastern','Atlantic');
INSERT INTO nhl (team,short,full,conf,div) values ('OTT','Senators','Ottawa Senators','Eastern','Northeast');
INSERT INTO nhl (team,short,full,conf,div) values ('PHI','Flyers','Philadelphia Flyers','Eastern','Atlantic');
INSERT INTO nhl (team,short,full,conf,div) values ('PHX','Coyotes','Phoenix Coyotes','Western','Pacific');
INSERT INTO nhl (team,short,full,conf,div) values ('PIT','Penguins','Pittsburgh Penguins','Eastern','Atlantic');
INSERT INTO nhl (team,short,full,conf,div) values ('SJS','Sharks','San Jose Sharks','Western','Pacific');
INSERT INTO nhl (team,short,full,conf,div) values ('STL','Blues','St. Louis Blues','Western','Central');
INSERT INTO nhl (team,short,full,conf,div) values ('TBL','Lightning','Tampa Bay Lighting','Eastern','Southeast');
INSERT INTO nhl (team,short,full,conf,div) values ('TOR','MapleLeafs','Toronto Maple Leafs','Eastern','Northeast');
INSERT INTO nhl (team,short,full,conf,div) values ('VAN','Canucks','Vancouver Canucks','Western','Northwest');
INSERT INTO nhl (team,short,full,conf,div) values ('WSH','Capitals','Washington Capitals','Eastern','Southeast');
INSERT INTO nhl (team,short,full,conf,div) values ('WPG','Jets','Winnipeg Jets','Eastern','Southeast');
