CREATE TABLE nhl (team TEXT PRIMARY KEY,short TEXT,full TEXT,conf TEXT,div TEXT,yahoo TEXT,espn TEXT,eid INTEGER);
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('ANA','Ducks','Anaheim Ducks','Western','Pacific','ana','ana','25');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('BOS','Bruins','Boston Bruins','Eastern','Northeast','bos','bos','1');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('BUF','Sabres','Buffalo Sabres','Eastern','Northeast','buf','buf','2');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('CGY','Flames','Calgary Flames','Western','Northwest','cgy','cgy','3');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('CAR','Hurricanes','Carolina Hurricanes','Eastern','Southeast','car','car','7');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('CHI','Blackhawks','Chicago Blackhawks','Western','Central','chi','chi','4');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('COL','Avalanche','Colorado Avalanche','Western','Northwest','col','col','17');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('CBJ','BlueJackets','Columbus Bluejackets','Western','Central','cob','cbj','29');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('DAL','Stars','Dallas Stars','Western','Pacific','dal','dal','9');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('DET','RedWings','Detroit Red Wings','Western','Central','det','det','5');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('EDM','Oilers','Edmonton Oilers','Western','Northwest','edm','edm','6');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('FLA','Panthers','Florida Panthers','Eastern','Florida','fla','fla','26');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('LAK','Kings','Los Angeles Kings','Western','Pacific','los','la','8');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('MIN','Wild','Minnesota Wild','Western','Northwest','min','min','30');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('MTL','Canadiens','Montreal Canadiens','Eastern','Northeast','mon','mtl','10');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('NSH','Predators','Nashville Predators','Western','Central','nas','nsh','27');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('NJD','Devils','New Jersey Devils','Eastern','Atlantic','njd','nj','11');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('NYI','Islanders','New York Islanders','Eastern','Atlantic','nyi','nyi','12');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('NYR','Rangers','New York Rangers','Eastern','Atlantic','nyr','nyr','13');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('OTT','Senators','Ottawa Senators','Eastern','Northeast','ott','ott','14');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('PHI','Flyers','Philadelphia Flyers','Eastern','Atlantic','phi','phi','15');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('PHX','Coyotes','Phoenix Coyotes','Western','Pacific','pho','phx','24');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('PIT','Penguins','Pittsburgh Penguins','Eastern','Atlantic','pit','pit','16');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('SJS','Sharks','San Jose Sharks','Western','Pacific','san','sj','18');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('STL','Blues','St. Louis Blues','Western','Central','stl','stl','19');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('TBL','Lightning','Tampa Bay Lighting','Eastern','Southeast','tam','tb','20');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('TOR','MapleLeafs','Toronto Maple Leafs','Eastern','Northeast','tor','tor','21');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('VAN','Canucks','Vancouver Canucks','Western','Northwest','van','van','22');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('WSH','Capitals','Washington Capitals','Eastern','Southeast','was','wsh','23');
INSERT INTO nhl (team,short,full,conf,div,yahoo,espn,eid) values ('WPG','Jets','Winnipeg Jets','Eastern','Southeast','wpg','wpg','28');
