CREATE TABLE nhl (team TEXT PRIMARY KEY,short TEXT,full TEXT,conf TEXT,div TEXT,yahoo TEXT);
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('ANA','Ducks','Anaheim Ducks','Western','Pacific','ana');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('BOS','Bruins','Boston Bruins','Eastern','Northeast','bos');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('BUF','Sabres','Buffalo Sabres','Eastern','Northeast','buf');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('CGY','Flames','Calgary Flames','Western','Northwest','cgy');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('CAR','Hurricanes','Carolina Hurricanes','Eastern','Southeast','car');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('CHI','Blackhawks','Chicago Blackhawks','Western','Central','chi');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('COL','Avalanche','Colorado Avalanche','Western','Northwest','col');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('CBJ','BlueJackets','Columbus Bluejackets','Western','Central','cob');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('DAL','Stars','Dallas Stars','Western','Pacific','dal');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('DET','RedWings','Detroit Red Wings','Western','Central','det');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('EDM','Oilers','Edmonton Oilers','Western','Northwest','edm');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('FLA','Panthers','Florida Panthers','Eastern','Florida','fla');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('LAK','Kings','Los Angeles Kings','Western','Pacific','los');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('MIN','Wild','Minnesota Wild','Western','Northwest','min');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('MTL','Canadiens','Montreal Canadiens','Eastern','Northeast','mon');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('NSH','Predators','Nashville Predators','Western','Central','nas');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('NJD','Devils','New Jersey Devils','Eastern','Atlantic','njd');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('NYI','Islanders','New York Islanders','Eastern','Atlantic','nyi');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('NYR','Rangers','New York Rangers','Eastern','Atlantic','nyr');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('OTT','Senators','Ottawa Senators','Eastern','Northeast','ott');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('PHI','Flyers','Philadelphia Flyers','Eastern','Atlantic','phi');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('PHX','Coyotes','Phoenix Coyotes','Western','Pacific','pho');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('PIT','Penguins','Pittsburgh Penguins','Eastern','Atlantic','pit');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('SJS','Sharks','San Jose Sharks','Western','Pacific','san');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('STL','Blues','St. Louis Blues','Western','Central','stl');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('TBL','Lightning','Tampa Bay Lighting','Eastern','Southeast','tam');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('TOR','MapleLeafs','Toronto Maple Leafs','Eastern','Northeast','tor');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('VAN','Canucks','Vancouver Canucks','Western','Northwest','van');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('WSH','Capitals','Washington Capitals','Eastern','Southeast','was');
INSERT INTO nhl (team,short,full,conf,div,yahoo) values ('WPG','Jets','Winnipeg Jets','Eastern','Southeast','wpg');
